#message:00:(NONE) {
	a[End]
}

#message:00:(Intro_0001) {
	[CenterX 159]Today...[End]
}

#message:00:(Intro_0002) {
	[CenterX 159]I'm going to tell the story of[BR]
	"Star Spirits and Good Wishes."[End]
}

#message:00:(Intro_0003) {
	[CenterX 159]Far, far away, beyond the sky,[End]
}

#message:00:(Intro_0004) {
	[CenterX 159]way above the clouds,[End]
}

#message:00:(Intro_0005) {
	[CenterX 159]it's been said that there's[BR]
	a haven where the Stars live.[End]
}

#message:00:(Intro_0006) {
	[CenterX 159]In the sanctuary of Star Haven[End]
}

#message:00:(Intro_0007) {
	[CenterX 159]there rests a fabled treasure[BR]
	called the Star Rod,[End]
}

#message:00:(Intro_0008) {
	[CenterX 159]which has the power to grant[BR]
	all wishes.[End]
}

#message:00:(Intro_0009) {
	[CenterX 159]Using this wondrous Star Rod,[BR]
	the seven revered Star Spirits[End]
}

#message:00:(Intro_000A) {
	[CenterX 159]watched over our peaceful world[End]
}

#message:00:(Intro_000B) {
	[CenterX 159]carefully...very carefully.[End]
}

#message:00:(Intro_000C) {
	[CenterX 159]And then...[End]
}

#message:00:(Intro_000D) {
	[CenterX 159]Oh dear... What the...?[End]
}

#message:00:(Intro_000E) {
	[CenterX 159]Who stuck that weird thing[BR]
	into this story?[End]
}

#message:00:(Intro_000F) {
	[CenterX 159]Ha ha ha! Yeah! I did![End]
}

#message:00:(Intro_0010) {
	[CenterX 159][Wave]Gwa ha ha ha ha ha ha ha!![BR]
	[/Wave][End]
}

#message:00:(Intro_0011) {
	[CenterX 159]So I can, at long last, beat my[BR]
	archenemy, Mario,[End]
}

#message:00:(Intro_0012) {
	[CenterX 159]I'll take this Star Rod![End]
}

#message:00:(Intro_0013) {
	[CenterX 159]Do it, Kammy Koopa!![End]
}

#message:00:(Intro_0014) {
	[CenterX 159][End]
}

#message:00:(Intro_0015) {
	[CenterX 159]No, you mustn't do that!![End]
}

#message:00:(Intro_0016) {
	[CenterX 159]Yeah! Now let's try using it![End]
}

#message:00:(Intro_0017) {
	[CenterX 159]Stop it! Cut it out, Bowser!![End]
}

#message:00:(Intro_0018) {
	[CenterX 159]You're changing the story!![End]
}

#message:00:(Intro_0019) {
	[CenterX 159]Bwa ha ha ha ha... We did it![End]
}

#message:00:(Intro_001A) {
	[CenterX 159]That was a piece o' cake!![BR]
	Gwaa ha ha![End]
}

#message:00:(Intro_001B) {
	[CenterX 159]Now Star Kids may rise to the[BR]
	Haven to deliver people's wishes...[End]
}

#message:00:(Intro_001C) {
	[CenterX 159]...but those wishes will not come[BR]
	true.[BR]
	[End]
}

#message:00:(Intro_001D) {
	[CenterX 159]Whatever can they do...?[End]
}

#message:00:(Intro_001E) {
	[Style right]
	Mail call![Wait][End]
}

#message:00:(Intro_001F) {
	[Style right]
	Hey, Mario![BR]
	[Pause 10]We got a letter from Princess[BR]
	Peach![Wait][End]
}

#message:00:(Intro_0020) {
	[Style right]
	I'll read it to you, OK?[Wait][End]
}

#message:00:(Intro_0021) {
	[Style right]
	All right, let's see...[Wait][End]
}

#message:00:(Intro_0022) {
	[Image index=0 pos=85,97 hasBorder=1 alpha=255 fadeAmount=15]
	[Yield][End]
}

#message:00:(Intro_0023) {
	[Style narrate]
	[Pause 4][InputOn]
	I'm throwing a party at my[BR]
	castle today![BR]
	[Pause 10]Mario and Luigi, I would be[BR]
	honored if you both could attend.[BR]
	[Wait][BR]
	[Next]
	[Down 5]Many guests from distant towns [BR]
	[Down 5]are hoping to meet you.[BR]
	[Wait][BR]
	[Up 10][Next]
	There will be tasty sweets and[BR]
	all kinds of entertainment![BR]
	I hope to see you here soon![BR]
	[Pause 15][Right 110]Sincerely, Peach[BR]
	[Wait][Yield][End]
}

#message:00:(Intro_0024) {
	[Style right]
	What a magnificent castle![BR]
	I never get used to this place.[BR]
	[Pause 10]It looks like lots of guests are[BR]
	already here.[Wait][End]
}

#message:00:(Intro_0025) {
	[Style right]
	Say, Mario, why don't you go see[BR]
	Princess Peach?[BR]
	[Pause 10]I'll go later. I'm thinking I'll[BR]
	mingle for now.[BR]
	[Wait][Next]
	If you press [A] in front of the[BR]
	door up there, you can open it.[Wait][End]
}

#message:00:(Intro_0026) {
	[Style right]
	Mario! Where are you going?[BR]
	[Wait][Next]
	The princess is expecting us![BR]
	You'd better at least say hello![Wait][End]
}

#message:00:(Intro_0027) {
	[Style right]
	Ah! Salutations, Mario! [BR]
	[Pause 10]Do you know Frost T. here?[BR]
	[Wait][Next]
	He's come all the way from the[BR]
	Shiver region, which lies far to[BR]
	the north of here.[Wait][End]
}

#message:00:(Intro_0028) {
	[Style right]
	Princess Peach is such a [BR]
	generous and wonderful lady,[BR]
	just as I was told. [BR]
	[Pause 10]It was worth coming to visit.[BR]
	[Wait][Next]
	Mario, please come visit us in[BR]
	the Shiver region someday![Wait][End]
}

#message:00:(Intro_0029) {
	[Style right]
	Mario, you're looking well![BR]
	[Pause 15]Please enjoy the party, OK?[Wait][End]
}

#message:00:(Intro_002A) {
	[Style right]
	Wow! I've never seen so many[BR]
	guests from different parts of[BR]
	the world in one place![BR]
	[Wait][Next]
	I'll bet you could hear some[BR]
	stories about places you've[BR]
	never been to, huh?[Wait][End]
}

#message:00:(Intro_002B) {
	[Style right]
	Hey...urp...Mario![BR]
	[Pause 10]I hope you brought an appetite![BR]
	There's so much good food here![BR]
	[Wait][Next]
	I already ate way too much...[BR]
	I'm taking a little breather.[BR]
	[Wait][Next]
	Well, [Pause 5]that's enough of a rest![BR]
	I'm hungry again! Let's eat![BR]
	To the buffet table!!! [Wait][End]
}

#message:00:(Intro_002C) {
	[Style right]
	I think Princess Peach has been[BR]
	looking forward to seeing you[BR]
	since this morning, Mario.[BR]
	[Wait][Next]
	She's been restless...[BR]
	[Pause 10]hee hee hee... [Pause 5]How cute...[Wait][End]
}

#message:00:(Intro_002D) {
	[Style right]
	Oh! Welcome, Mario![BR]
	[Pause 10]The last party was lovely,[BR]
	wasn't it?[BR]
	[Wait][Next]
	Oh! By the way,[BR]
	[Pause 10]Princess Peach has been waiting[BR]
	for you.[Wait][End]
}

#message:00:(Intro_002E) {
	[Style right]
	Welcome to Peach's Castle![Wait][End]
}

#message:00:(Intro_002F) {
	[Style right]
	Princess Peach went into her[BR]
	private chambers just now.[BR]
	[Wait][Next]
	She must be a bit tired.[Wait][End]
}

#message:00:(Intro_0030) {
	[Style right]
	Wow...[BR]
	[Pause 10]This castle is absolutely[BR]
	breathtaking, don't you think?[BR]
	[Wait][Next]
	I wish I could stay here at[BR]
	Peach's Castle forever![Wait][End]
}

#message:00:(Intro_0031) {
	[Style right]
	Oh, hello there, Mario![BR]
	[Pause 10]I'm Tayce T.[BR]
	[Pause 10]I really love to cook![HEART][BR]
	[Wait][Next]
	You may not know this, but I[BR]
	cooked all the food for this big[BR]
	party. I made all of my most[BR]
	delicious dishes![HEART][BR]
	[Wait][Next]
	But... Oh dear...[BR]
	[Pause 10]I got so into my cooking that I[BR]
	used up all of my ingredients![BR]
	[Wait][Next]
	Now I have to go shopping![Wait][End]
}

#message:00:(Intro_0032) {
	[Style right]
	I've been practicing cooking.[BR]
	[Wait][Next]
	I hope that someday I get good[BR]
	enough to cook food as delicious[BR]
	as Tayce T.'s.[BR]
	[Wait][Next]
	Do you know how to cook, Mario?[BR]
	You really ought to learn![BR]
	[Pause 10]Personally, I think cooking is[BR]
	exceptionally fun![Wait][End]
}

#message:00:(Intro_0033) {
	[Style right]
	Greetings, Mario![BR]
	[Pause 10]I am the Minister of Princess[BR]
	Peach's Castle.[BR]
	[Wait][Next]
	It's good to see you here. When[BR]
	you're around, I feel like our[BR]
	kingdom is secure.[BR]
	[Pause 10]Yep, our future looks bright![Wait][End]
}

#message:00:(Intro_0034) {
	[Style right]
	I come from a desert town called[BR]
	Dry Dry Outpost. [BR]
	[Wait][Next]
	This castle is really lovely, isn't[BR]
	it? Truly gorgeous. So cool and[BR]
	comfortable...[BR]
	[Wait][Next]
	I even got a chance to talk to[BR]
	the beautiful Princess Peach.[BR]
	[Wait][Next]
	What an honor! When I return to[BR]
	Dry Dry Outpost, I'm going to[BR]
	tell everyone about it.[Wait][End]
}

#message:00:(Intro_0035) {
	[Style right]
	I'm a Nomadimouse, and I come[BR]
	from Dry Dry Desert.[BR]
	[Wait][Next]
	Everyone I've met in this town[BR]
	seems incredibly nice.[BR]
	[Pause 10]I think I'll make this place my[BR]
	home away from home.[Wait][End]
}

#message:00:(Intro_0036) {
	[Style right]
	I'm here on behalf of lovely[BR]
	Shiver City. I'm the Mayor there,[BR]
	you know![BR]
	[Wait][Next]
	My goodness, look at the time![BR]
	[Pause 10]I have to go shopping for[BR]
	souvenirs with Frost T.![Wait][End]
}

#message:00:(Intro_0037) {
	[Style right]
	I come from Koopa Village, which[BR]
	is just down the road from here.[BR]
	[Wait][Next]
	Ohhh... I just had the honor of[BR]
	talking with Princess Peach![BR]
	[Pause 10]What a wonderful lady she is![HEART][Wait][End]
}

#message:00:(Intro_0038) {
	[Style right]
	Well... [Pause 5]Today, we have guests[BR]
	[Pause 10]from Dry Dry Outpost, the[BR]
	Shiver region, Koopa Village...[BR]
	[Wait][Next]
	There're so many folks here,[BR]
	I can't keep track of them all.[BR]
	[Wait][Next]
	And where might you be from?[BR]
	[Pause 20]Oh... [Pause 10]You're Mario!?[BR]
	[Pause 10]I... [Pause 5]I'm sorry! Excuse me![Wait][End]
}

#message:00:(Intro_0039) {
	[Style right]
	Does Princess Peach have a[BR]
	special man in her life?[BR]
	[Wait][Next]
	She's such a lovely lady...[BR]
	Whoever she loves must be very[BR]
	special indeed...[Wait][End]
}

#message:00:(Intro_003A) {
	[Style right]
	Do you know of a place called[BR]
	Shooting Star Summit?[BR]
	[Pause 10]It's near this castle. It's such[BR]
	a romantic place...[BR]
	[Wait][Next]
	It's definitely the best place[BR]
	for a date. Trust me. [BR]
	[Pause 10]Maybe you ought to, you know,[BR]
	ask the princess to go there...[Wait][End]
}

#message:00:(Intro_003B) {
	[Style right]
	Hello, Mario.[BR]
	[Pause 10]I am always on the cutting edge[BR]
	of fashion, and I must say...[BR]
	[Wait][Next]
	...your outfit is just fabulous. [BR]
	[Pause 10]It really suits you![HEART][Wait][End]
}

#message:00:(Intro_003C) {
	[Style right]
	I... [Pause 5]I'm just a trainee, sir.[BR]
	[Wait][Next]
	So many guests... My heart's[BR]
	been beating like a bass drum[BR]
	ever since this morning...[BR]
	[Wait][Next]
	[PrintRising]Thump [Pause 3]thump [Pause 3]thump [Pause 3]thump[/PrintRising][Pause 3]...[Wait][End]
}

#message:00:(Intro_003D) {
	[Style right]
	This is Princess Peach's room,[BR]
	[Pause 20]but I'm afraid she isn't in here [BR]
	at the moment.[Wait][End]
}

#message:00:(Intro_003E) {
	[Style right]
	Huh?[BR]
	[Pause 20]Oh no! Absolutely not![BR]
	[Wait][Next]
	I don't think it's very polite to[BR]
	go into her room without asking[BR]
	her first, Mario! [Wait][End]
}

#message:00:(Intro_003F) {
	[Style right]
	I said NO, and that means NO.[BR]
	[Pause 10]You are simply not allowed to go[BR]
	in there![Wait][End]
}

#message:00:(Intro_0040) {
	[Style right]
	Boy, you're persistent![BR]
	[Pause 15]I guess I have no choice...[BR]
	[Wait][Next]
	Hurry up in there, though--[BR]
	and don't touch anything![Wait][End]
}

#message:00:(Intro_0041) {
	[Style right]
	I envy you, Mario...[Wait][End]
}

#message:00:(Intro_0042) {
	[Style right]
	How was it?[BR]
	[Pause 10]To tell you the truth, I've never[BR]
	seen the inside of her room...[Wait][End]
}

#message:00:(Intro_0043) {
	[Style inspect]
	What a big fireplace![BR]
	[Pause 10]And what a cozy fire![Wait][End]
}

#message:00:(Intro_0044) {
	[Style inspect]
	Her dresses are beautiful, but[BR]
	they all look the same![BR]
	[Pause 10]This must be her favorite style[BR]
	of dress.[Wait][End]
}

#message:00:(Intro_0045) {
	[Style inspect]
	These are cosmetics.[BR]
	[Pause 10]Mario looks fine without them.[Wait][End]
}

#message:00:(Intro_0046) {
	[Style inspect]
	A framed photo of Mario![Wait][End]
}

#message:00:(Intro_0047) {
	[Style inspect]
	Quite a fluffy bed.[BR]
	[Pause 10]It looks like this bed was[BR]
	designed for sweet dreams.[Wait][End]
}

#message:00:(Intro_0048) {
	[Style inspect]
	A vase full of lovely flowers.[BR]
	[Pause 10]They smell heavenly.[Wait][End]
}

#message:00:(Intro_0049) {
	[Style right]
	It's nice and quiet here with[BR]
	no guests around.[BR]
	[Pause 10]Ahh...so pleasant.[Wait][End]
}

#message:00:(Intro_004A) {
	[Style right]
	Princess Peach went into her[BR]
	private chambers just now.[Wait][End]
}

#message:00:(Intro_004B) {
	[Style right]
	Oh, Mario![BR]
	[Pause 10]You came to the party to see[BR]
	me! You're so sweet![BR]
	[Pause 20]Thank you![HEART][Wait][End]
}

#message:00:(Intro_004C) {
	[Style right]
	I was just resting a bit. It[BR]
	gets tiring, greeting all those[BR]
	guests out there![BR]
	[Wait][Next]
	Nobody will bother us here.[BR]
	[Pause 10]Shall we relax and chat, just the[BR]
	two of us? [Wait][End]
}

#message:00:(Intro_004D) {
	[Style right]
	It was a lovely day today, so I'm[BR]
	sure it's comfortable out on the[BR]
	balcony right now.[BR]
	[Pause 10]Would you accompany me, Mario?[Wait][End]
}

#message:00:(Intro_004E) {
	[Style right]
	Wait a second...[BR]
	[Pause 10]Do you hear that, Mario?[Wait][End]
}

#message:00:(Intro_004F) {
	[Style right]
	Oh my! Look, Mario![BR]
	[Pause 10]Something's coming straight[BR]
	towards the window! 
	[Pause 10]Watch out![Wait][End]
}

#message:00:(Intro_0050) {
	[Style right]
	[Voice bowser]
	[PrintRising]Gwaa ha ha ha ha ha![BR]
	[/PrintRising][Pause 5]Long time no see,[BR]
	Princess Peach![Wait][End]
}

#message:00:(Intro_0051) {
	[Style right]
	... Bowser![BR]
	[Pause 10]What do you think you're doing?![BR]
	You can't just barge in![BR]
	You weren't even invited![Wait][End]
}

#message:00:(Intro_0052) {
	[Style right]
	[Voice bowser]
	[Down 8][PrintRising][Wave][Size 32,32]
	Gwa ha ha ha![BR]
	[SizeReset]
	[/PrintRising][/Wave][Wait][BR]
	[Scroll 3][Up 12]Give me break![BR]
	You should be honored that[BR]
	a cool guy like me even[BR]
	showed up to your lame party![Wait][End]
}

#message:00:(Intro_0053) {
	[Style right]
	[Voice bowser]
	Huh!? What?[BR]
	[Pause 10]It's...Mario!![BR]
	[Wait][Next]
	Ha! That's perfect![BR]
	[Pause 10]It just wouldn't feel right[BR]
	nabbing the princess without[BR]
	stomping you first.[Wait][End]
}

#message:00:(Intro_0054) {
	[Style right]
	Haven't you learned your lesson[BR]
	by now, Bowser?[BR]
	[Wait][Next]
	You can never defeat Mario![BR]
	[Pause 10]Why don't you give up already?[Wait][End]
}

#message:00:(Intro_0055) {
	[Style right]
	[Voice bowser]
	True, true, I have had my[BR]
	problems in the past...[BR]
	[Pause 10]But you can't blame[BR]
	a guy for trying![BR]
	[Wait][Next]
	[PrintRising]This time I'm gonna win![Wait][End]
}

#message:00:(Intro_0056) {
	[Style right]
	[Voice bowser]
	OK, tough guy![BR]
	[Pause 10]Let's go![Wait][End]
}

#message:00:(Intro_0057) {
	[Style right]
	Mario, [Pause 5]you can do it![Wait][End]
}

#message:00:(Intro_0058) {
	[Style right]
	[Voice bowser]
	Good old Mario...always fighting.[BR]
	[Pause 10]You're a thorn in my side.[BR]
	[Wait][Next]
	But today, your pathetic little[BR]
	attacks won't beat me![Wait][End]
}

#message:00:(Intro_0059) {
	[Style right]
	[Voice bowser]
	Take a look at this![BR]
	[Pause 5]Look what I stole from Star[BR]
	Haven! It's the [Color 0x20]Star Rod[Color 0xA]![BR]
	[Wait][Next]
	This fine piece of work has the[BR]
	power to grant any wish in the[BR]
	whole wide world![BR]
	[Wait][Next]
	And when I use the Star Rod to[BR]
	increase my strength, even you[BR]
	can't beat me, Mario![Wait][End]
}

#message:00:(Intro_005A) {
	[Style right]
	[Voice bowser]
	[PrintRising]Gwa ha ha ha ha ha![BR]
	[/PrintRising]How do you like that, Mario?![Wait][End]
}

#message:00:(Intro_005B) {
	[Style right]
	[Voice bowser]
	[PrintRising]Gwa ha ha ha ha ha![BR]
	[/PrintRising][Pause 5]Is that all you've got? How sad![BR]
	You'd best take some vitamins,[BR]
	'cause that didn't hurt at all![Wait][End]
}

#message:00:(Intro_005C) {
	[Style right]
	[Voice bowser]
	Yup, just as I expected. Mario's[BR]
	no match for the new me.[BR]
	[Wait][Next]
	It's not even worth my time to[BR]
	toy with you anymore, Mario.[BR]
	[Pause 10]It's time to end this![BR]
	[Wait][Next]
	Here we go, Mario![BR]
	[PrintRising]Good night![Wait][End]
}

#message:00:(Intro_005D) {
	[Style right]
	Mario! Are you alright?[BR]
	[Wait][Next]
	I'm glad you're okay, but that[BR]
	really looked dangerous![BR]
	Don't worry me like that![Wait][End]
}

#message:00:(Intro_005E) {
	[Style right]
	[Voice bowser]
	Ow...[BR]
	[Pause 10]I really thought...[BR]
	[Pause 10]thought I had you this time...[BR]
	[Wait][End]
}

#message:00:(Intro_005F) {
	[Style right]
	You musn't let this defeat[BR]
	keep you down, Your Bitterness![BR]
	[Wait][Next]
	These fools won't look so smug[BR]
	when you tell them your true[BR]
	purpose in coming here.[Wait][End]
}

#message:00:(Intro_0060) {
	[Style right]
	[Voice bowser]
	Oh, right![BR]
	I got so caught up with thrashing[BR]
	Mario, I almost forgot.[BR]
	[Wait][End]
}

#message:00:(Intro_0061) {
	[Style right]
	[Voice bowser]
	C'mon, Kammy,[BR]
	let's go rally the troops![BR]
	[Wait][End]
}

#message:00:(Intro_0062) {
	[Style right]
	[PrintRising]Oh, no! Mario------!![Wait][End]
}

#message:00:(Intro_0063) {
	[Style right]
	Sorry, sir![BR]
	I mean, Mario! Sir Mario![BR]
	Er... what I mean is...[BR]
	[Pause 10]Please don't go in there![BR]
	[Wait][Next]
	After that commotion with Bowser,[BR]
	the hallway is a huge mess...[BR]
	there's broken glass everywhere.[BR]
	[Wait][Next]
	I was instructed to keep[BR]
	all the guests in the[BR]
	main hall until they[BR]
	clean things up.[BR]
	[Wait][End]
}

#message:00:(Intro_0064) {
	[Style right]
	Don't go easy on him, Mario![BR]
	[Wait][Next]
	Press the [A] button when[BR]
	you're about to land on him[BR]
	and give him the old one-two![BR]
	[Wait][Next]
	[Pause 2].[Pause 2].[Pause 2].[Pause 2].[Pause 2].[BR]
	[Pause 10]...Ahem. I mean...[BR]
	[Wait][Next]
	You can do it, Mario![BR]
	[Wait][End]
}

#message:00:(Intro_0065) {
	[Style right]
	[Voice bowser]
	I've gotten real tired of losing[BR]
	to you Mario.[BR]
	[Wait][Next]
	We all know you can beat me in[BR]
	a one-on-one battle, as much as[BR]
	I hate to admit it.[BR]
	[Wait][Next]
	Well, it's time for you to play[BR]
	by MY rules.[BR]
	[Yield][End]
}

#message:00:(Intro_006A) {
	[Wait][Next]
	[Style right]
	[Voice bowser]
	That's why I'm going to war with[BR]
	the Mushroom Kingdom![BR]
	[Yield][End]
}

#message:00:(Intro_0066) {
	[Wait][Next]
	[Style right]
	[Voice bowser]
	In 30 days, all my strongest[BR]
	guys will be here to destroy[BR]
	this kingdom of wimps![BR]
	[Wait][End]
}

#message:00:(Intro_0067) {
	[Style right]
	[Voice bowser]
	[Down 8][PrintRising][Wave][Size 32,32]
	Gwa ha ha ha![BR]
	[SizeReset]
	[/PrintRising][/Wave][BR]
	[Wait][End]
}

#message:00:(Intro_0068) {
	[Style right]
	Oh, Mario, this is terrible![BR]
	[Wait][Next]
	We can't go to war with[BR]
	the Koopa Kingdom![BR]
	[Wait][Next]
	I swore to make this kingdom[BR]
	a peaceful place for as long[BR]
	as I was princess.[BR]
	[Wait][Next]
	Well...[Pause 10] it's lucky that I've[BR]
	been working on a project to[BR]
	keep the citizens safe from[BR]
	trouble like this.[BR]
	[Wait][Next]
	I want to foster more heroes[BR]
	like yourself in the[BR]
	Mushroom Kingdom.[BR]
	[Wait][Next]
	You have done so much to[BR]
	help defend our kingdom,[BR]
	but even you can't be[BR]
	everywhere at once.[BR]
	[Wait][Next]
	I just know there must be[BR]
	other people out there who[BR]
	want to use their skills to[BR]
	help others![BR]
	[Wait][Next]
	We just need to show them how![BR]
	[Pause 10]Would you help me find[BR]
	these new heroes and train them?[BR]
	[Wait][End]
}

#message:00:(Intro_0069) {
	[Style right]
	Thank you, Mario.[BR]
	I'm eternally grateful for[BR]
	your support.[BR]
	[Wait][Next]
	I'm sorry, but I must go now[BR]
	and calm down the guests.[BR]
	Please talk to the Minister[BR]
	for details on the project.[BR]
	[Wait][End]
}
